### ISSUE TITLE
Prevent PWA double submission

### ISSUE THREAD

**Issue by andreban** [GoogleChromeLabs/gulliver#203]
If two different users submit the same PWA at the same time, it's still possible to have a double PWA submission.

The manifest url is not the primary key for the PWA, and it shouldn't be, since a PWA can have it's manifest Url updated. 

Since cloud-datastore doesn't offer a unique-key feature. The solution would be to emulate one by creating a secondary table where the manifest-url is the primary key, and trying to insert to both tables inside a transaction. If the insertion on the manifest-url table fails, we know it's a duplicated submission and we can fallback to finding the PWA and returning it in code.

When we implement updating / deleting a PWA, we'll need to work with both tables too.

**Comment by andreban** [comment]
This is related to #201

**Comment by juliantoledo** [comment]
@andreban was this fix with the counter transaction code?

**Comment by andreban** [comment]
No, this is a different issue.
