### ISSUE TITLE
Human readable PWA name in URL path

### ISSUE THREAD

**Issue by sebastianbenz** [GoogleChromeLabs/gulliver#224]
For example, instead of: 

https://pwa-directory.appspot.com/pwas/5692592335355904

use the slugified version of the PWA name, e.g.:

https://pwa-directory.appspot.com/pwas/amp-by-example

**Comment by juliantoledo** [comment]
- [ ] Create a slugified field for the PWA object, update all PWAs
- [ ] Create a new router to handle slugified URLs
- [ ] 301 redirect from ID URLs to slugified URLs
- [ ] Change the home screen to use slugified URLs

**Comment by ithinkihaveacat** [comment]
Does https://www.npmjs.com/package/slug guarantee that unique input strings map to different "slugified" strings? We might need URLs with both the slug and the unique id, like <https://pwa-directory.appspot.com/pwas/5692592335355904/amp-by-example>.

**Comment by sebastianbenz** [comment]
Maybe use a URI encoded version of the PWA URL:

```
> encodeURI('ampbyexample.com')
'ampbyexample.com'
```

These should be unique.

**Comment by juliantoledo** [comment]
I am currently checking if the slugified name is unique when is generated and fallback in this order:  Name -> Description -> Id.

**Comment by sebastianbenz** [comment]
That sounds a lot more complicated than simply using the URL...

**Comment by juliantoledo** [comment]
@sebastianbenz very true. Let me try with the URL removing parameters.

**Comment by juliantoledo** [comment]
For www.domain.com/folder/
What do you think is better?
www.domain.com/folder/
www.domain.com%2Ffolder%2F
www.domain.com-folder

**Comment by sebastianbenz** [comment]
I'd go with `www.domain.com%2Ffolder%2F`:

* `www.domain.com/folder/` makes it impossible to use the path for PWA actions, e.g. `.../pwas/ampbyexample.com/edit/`
* `www.domain.com-folder` is not unique as it is also a valid URL

=> ` www.domain.com%2Ffolder%2F`

**Comment by juliantoledo** [comment]
@sebastianbenz @ithinkihaveacat done, I updated #242

**Comment by juliantoledo** [comment]
I created a branch to keep working on this:
https://github.com/GoogleChrome/gulliver/tree/encoded-start-url

The problem with the start_url is that it may change, for example, they could remove the folder. Once we start sharing/exporting those URLs we may need to keep track of those changes to handle redirects or create a slugifed version that never changes.
