### ISSUE TITLE
"Add PWA" button is clickable at all times

### ISSUE THREAD

**Issue by ithinkihaveacat** [GoogleChromeLabs/gulliver#266]
The "Add PWA" button though responds to taps/clicks at all times, even when "disabled" (greyed out). It should be completely inactive when the user is not logged in.

/cc @sebastianbenz

**Comment by sebastianbenz** [comment]
The problem is: how can users learn that they need to be logged in to add pwas?

**Comment by ithinkihaveacat** [comment]
True. My recollection is that we decided to punt on UX improvements (e.g. a "merged" button) until we have more features available that required login, like ratings.

**Comment by davmillar** [comment]
In [the version that's live](https://pwa-directory.appspot.com/), the does not seem to be clickable at all times. However, the LOGIN button does not seem to function either.

**Comment by UlisesGascon** [comment]
I will work on it @juliantoledo!

**Comment by nhoizey** [comment]
@sebastianbenz we learn from the error message:

![image](https://user-images.githubusercontent.com/78213/39655371-89a22aa8-4ff9-11e8-9800-ed29a029a534.png)

And the login button still doesn't do anything. I get this error in the console:

![image](https://user-images.githubusercontent.com/78213/39655412-be32d876-4ff9-11e8-8c26-fc98da59ffed.png)

**Comment by andreban** [comment]
@nhoizey Looks like the JS required for sign-in has not been loaded. Can you provide information on browser vendor and version?

**Comment by andreban** [comment]
I've been able to reproduce on Safari and it looks like one of the libraries used by the Login API is breaking.

<img width="1202" alt="screen shot 2018-05-06 at 9 52 13 am" src="https://user-images.githubusercontent.com/1733592/39671616-57922174-5113-11e8-9015-619e896f5226.png">
