### ISSUE TITLE
Automatically derive manifests from app pages

### ISSUE THREAD

**Issue by slightlyoff** [GoogleChromeLabs/gulliver#323]
The current [submission form](https://pwa-directory.appspot.com/pwas/add) asks for a PWA Manifest URL (e.g. `https://airhorner.com/manifest.json`, not `https://airhorner.com/`). It seems as though it'd be much more user-friendly to be able to submit any URL from the PWA which points at the Manifest. The tuple of (discovered) manifest location and the `start_url` from the manifest should be enough to uniquely identify the app.

**Comment by andreban** [comment]
Agreed. We were looking into implementing this by looking for the manifest link on the page, but it seems it can also be added using Javascript. #190 was tracking this, but I didn't realize we had closed it.

**Comment by juliantoledo** [comment]
We have support to submit by start_url, however we are using the manifest URL and not the tuple as unique identifier. We'll change it.

**Comment by ithinkihaveacat** [comment]
`[manifest_url, start_url]` doesn't uniquely identify a PWA if a site versions its manifest. This is done by e.g. `https://weather.com/weather/today/l/12345` which currently has a manifest of `https://weather.com/weather/assets/manifest.507fcb498f4e29acfeed7596fe002857.json`.

This might be an unanticipated side effect of an over-enthusiastic build process, but nevertheless, "versioning" the manifest URL and serving it with an infinite expiry doesn't seem like an outrageous thing to want to do.

**Comment by slightlyoff** [comment]
Weather.com should not version these URLs (same for their serviceworker).
This is a bug with their site, not with how we identify apps.

On Mon, Jun 19, 2017 at 6:12 AM, Michael Stillwell <notifications@github.com

**Comment by adewale** [comment]
See also: https://github.com/w3c/manifest/issues/586
