### ISSUE TITLE
Build a service worker 'kill-switch'

### ISSUE THREAD

**Issue by adewale** [GoogleChromeLabs/gulliver#325]
Provide a kill-switch as described here: http://stackoverflow.com/questions/33986976/how-can-i-remove-a-buggy-service-worker-or-implement-a-kill-switch which can be used to force an update of the service worker for all users when we believe that something has gone wrong with the service worker that's installed for a significant number of users. This means we wouldn't have to tell all users to manually update their service workers.

**Comment by adewale** [comment]
This article: https://medium.com/@boopathi/service-workers-gotchas-44bec65eab3f#.jfg4k91mi also has some relevant guidance.

**Comment by sebastianbenz** [comment]
We're already implementing the recommendations by Jeff:

* max-age 0
* versioning with cache clearance on update
