### ISSUE TITLE
Reorganize Source Code

### ISSUE THREAD

**Issue by andreban** [GoogleChromeLabs/gulliver#345]
I'm thinking about reorganizing the source code a bit, so it becomes easier to navigate. It would also improve on JS transpilation, as the source code would be on a different folder from the result. Here are my initial thoughts on the structure.
```
root
    app
        controllers
        lib
        middlewares
        model
    views - Handlebars templates go here. Maybe this should be inside app?
        includes
        helpers
    wwwsrc - Static content sources
        js
        css
    public - static content goes here after build. Should not be committed.
        js
        css
        img
         ...
    scripts -  scripts used on the build process
    config -  config files for rollup, gulp, babel, etc.
```

@sebastianbenz @juliantoledo

**Comment by ithinkihaveacat** [comment]
I think the config files should stay in the root—it's a bit untidy but I've never seen them anywhere else and most of the tools look there by default.

`wwwsrc` feels a bit awkward. Maybe just `src`? Or divide the code into `client` and `server`?

**Comment by sebastianbenz** [comment]
few comments:

* views should go into app
* s/app/backend/ -> the app is actually the client
* s/wwwsrc/app/ -> see above
* s/public/app\/dist/ -> dist is commonly used and should go into the app dir

**Comment by andreban** [comment]
Summarizing, something like this:
```
root
    backend
        controllers
        lib
        middlewares
        model
        views - Handlebars templates go here. 
        	    includes
            helpers
    app - Static content sources
        src
            js
            css
            img
            …
        dist
            js
            css
            img
            ...
    scripts -  scripts used on the build process
    .babelrc.js
    package.json
