### ISSUE TITLE
Lighthouse score not being refreshed in app detail page

### ISSUE THREAD

**Issue by mcmd** [GoogleChromeLabs/gulliver#430]
Tak for distance app https://pwa-directory.appspot.com/pwas/5724107450613760

The score next to the lighthouse icon reads "55", but you can see in the chart that the current score is 91 (if I run lighthouse for that app I get the same score, 91).

It seems like the score shown is not being refreshed with the one obtained in latest execution of lighthouse?

See screenshot:

![sr2hacjihla](https://user-images.githubusercontent.com/868584/28316399-a3ae53c8-6bba-11e7-899e-97453d7e73ba.png)

The same happens in the listing of the app:

![screen shot 2017-07-18 at 1 14 29 pm](https://user-images.githubusercontent.com/868584/28316515-1c732cc0-6bbb-11e7-955e-6ba01e537c26.png)

**Comment by juliantoledo** [comment]
Fixed
