### ISSUE TITLE
H2 connection upgrade hanging 

### ISSUE THREAD

**Issue by juliantoledo** [GoogleChromeLabs/gulliver#434]
Adding this manifest causes the H2 connection upgrade to hang:
https://ethanmarcotte.com/manifest.json

**Comment by juliantoledo** [comment]
Seems like https://adaptivewebdesign.info/1st-edition/read/manifest.json is also broken now.

**Comment by midzer** [comment]
Yeah, seems like you cannot add new `manifest.json` right now. Save buttons is greyed out, too.

There are two errors in console right now:
- getSubscriptions() in `messaging.js`
- `idpiframe_initialization_failed`

**Comment by andreban** [comment]
I've created a bug for `getSubscriptions` here: https://github.com/GoogleChromeLabs/gulliver/issues/441
