### ISSUE TITLE
Console shows `idpiframe_initialization_failed`error

### ISSUE THREAD

**Issue by andreban** [GoogleChromeLabs/gulliver#442]
@midzer - It seems this error is related to having 3rd party cookies disabled and Google Sign-in. Here's more information on it:

- https://stackoverflow.com/questions/42668299/google-auth-api-javascript-idpiframe-initialization-error-on-chrome
- https://github.com/google/google-api-javascript-client/issues/260

Can you confirm if this would be the case?

**Comment by midzer** [comment]
@andreban yeah, without blocking 3rd party cookies this error message disappears for me in Chromium 60 console

**Comment by andreban** [comment]
Thanks for confirming - The main consequence is that users become unable to login when the 3rd party cookies are disabled. There's no workaround we can do to make it work, but we should consider communicating to the user that they are unable to login because 3rd party cookies are disabled.
There are 2 approaches we can take:
1) When the page loads, if the error happens, show a toast at the bottom of the screen and disable the login button.
2) Don't show anything when the page loads, but show the toast when the user tries to login (clicks the login button).
