### ISSUE TITLE
Some audit results don't make sense

### ISSUE THREAD

**Issue by samdutton** [GoogleChromeLabs/gulliver#456]
Just looking at the report for https://simpl.info:

![image](https://user-images.githubusercontent.com/205226/34829839-e40f97f6-f6d9-11e7-8ccf-4208ecda8965.png)

Not sure why these three audits are coming up as false:

- The home page https://simpl.info/index.html doesn't require JavaScript to load, and only uses well supported HTML and CSS, so I'm not sure why 'Site works cross-browser' is false.
- There are no 'page transitions', so not sure where the Page transitions don't feel like they block on the network' warning is coming from.
- Every page on the site does have a unique URL.

The performance score is only 41 — which doesn't tally with the site's performance measured using Lighthouse from Chrome DevTools. Is that because some audits failed?

![image](https://user-images.githubusercontent.com/205226/34830092-c0a2c10c-f6da-11e7-9790-42d3bb1b3fb0.png)

Also, the Best Practices score isn't 100, but there's no reason given:

![image](https://user-images.githubusercontent.com/205226/34830063-a12e33d8-f6da-11e7-86b3-18fb84f1be44.png)

**Comment by juliantoledo** [comment]
@samdutton I will investigate it tomorrow, I should also test and deploy LH 2.7.0 soon.

**Comment by juliantoledo** [comment]
The 3 checks that come as false are the "Additional items to manually check" in the Lighthouse report, we need to remove them or change the format we use to display them.

I will do few changes to the whole section, ideally we should find a way to export our json to the Lighthouse report viewer.

**Comment by samdutton** [comment]
Thanks @juliantoledo!

**Comment by nunoperalta** [comment]
Hello,

I was wondering the exact same thing for those 3 audits being 'false' for https://similarworlds.com !!

When I used Lighthouse through Google Chrome, I was getting score 100.

I'm glad this is being looked at :)

Thank you very much.

**Comment by juliantoledo** [comment]
We now link to the full LH report in the lighthouse-viewer, our lighthouse-viewer is for LH 2.9.1 and tomorrow our reports will match that version.
