### ISSUE TITLE
Hability to remove a PWA I submitted

### ISSUE THREAD

**Issue by cmdalbem** [GoogleChromeLabs/gulliver#458]
The user might have been testing the platform but wasn't intending to publicly expose his app yet.

(that's my case ;)

Thanks!

**Comment by juliantoledo** [comment]
We could allow the same user to be able to remove it. I will set this as a feature request.

I can manually delete yours if you want.

**Comment by cmdalbem** [comment]
Thanks @juliantoledo! Giving this ability to the same user who submitted it sounds like a good idea.
And yes I'd be happy if you could manually remove my entry. It's only in portuguese for now so I don't think it's of any use to the general community yet.
