### ISSUE TITLE
Start URL shouldn't be extracted from manifest

### ISSUE THREAD

**Issue by cmdalbem** [GoogleChromeLabs/gulliver#459]
For my PWA I use a special start URL with a **utm_source=homescreen** that helps me keep track of who is using my PWA from their home screen. Now that I've submitted my PWA to the repository I have people landing on it from this URL with the UTM_SOURCE and it's skewing my Analytics.
One solution would be to point to the original domain from where the manifest was extracted instead of the start_url field from the manifest.

**Comment by andreban** [comment]
Setting the link to the original domain wouldn't work, in the case of a PWA being served on a subdirectory. Another options may be to remove all the `utm_*` parameters from `start_url`. @juliantoledo, WDYT?

**Comment by juliantoledo** [comment]
We have seen this for other PWAs as well, we still need to use start_url.

We could remove parameters or overwrite the UTM_SOURCE to pwa-directory, I think that is the most common parameter.

**Comment by cmdalbem** [comment]
Yea, automatically removing the UTM_SOURCE from the URL sounds like a good and generic solution.

**Comment by cmdalbem** [comment]
Is the merged solution retroactive? If not I guess my original issue isn't fully solved.

**Comment by andreban** [comment]
It is. It changes the URL before rendering, not before saving.

**Comment by cmdalbem** [comment]
I see! I guess it just wasn't deployed yet, then.
(I'm looking at this PWA here, still has the `utm_source` in the link: https://pwa-directory.appspot.com/pwas/5958460972728320)

**Comment by andreban** [comment]
Looks like it wasn't deployed yet. @juliantoledo can confirm.

**Comment by juliantoledo** [comment]
Exactly, we still need to deploy it.

**Comment by cmdalbem** [comment]
Cool, thanks guys.
