### ISSUE TITLE
feat(Add in RSS feed of latest sites)

### ISSUE THREAD

**Issue by PaulKinlan** [GoogleChromeLabs/gulliver#463]
I have ideas and plans. Would love to get an RSS feed of the latest.

**Comment by juliantoledo** [comment]
It sounds interesting, let's see if we can do it soon.

**Comment by juliantoledo** [comment]
@PaulKinlan https://pwa-directory.appspot.com/api/pwa/?format=rss&limit=100

**Comment by PaulKinlan** [comment]
curl https://pwa-directory.appspot.com/api/pwa/?format=rss&limit=100 works great thanks, one thing I noticed though is that if I view it through the web, the appshell hosts the page


![screen shot 2018-03-01 at 7 21 08 am](https://user-images.githubusercontent.com/45510/36811325-7970df22-1d21-11e8-8a28-f0e2a9142b8d.png)

**Comment by andreban** [comment]
I noticed it too. Created #466 sooner today to track it.

**Comment by juliantoledo** [comment]
We fixed the app shell issue on #467 it should work once the SW updates.

@PaulKinlan does the way we set the content in <content:encoded> work for you? Please let us know if we should set it up differently.
