### ISSUE TITLE
Submit WPA issue

### ISSUE THREAD

**Issue by rob-baker** [GoogleChromeLabs/gulliver#470]
https://pwa-directory.appspot.com/pwas/add
Doesn't seem to be working, the Save button is always disabled.

I've been trying to submit my new PWA:
https://www.pathuku.com/hostileshapes/manifest.json

What am I doing wrong?

**Comment by andreban** [comment]
Uses need to be logged in to submit PWAs. Can you confirm you are logged in?

**Comment by rob-baker** [comment]
I was not logged in. App now submited. Thanks for your help.
