### ISSUE TITLE
Metrics not being triggered

### ISSUE THREAD

**Issue by iondrimba** [GoogleChromeLabs/gulliver#474]
Metrics not being triggered on these two new demos.

https://pwa-directory.appspot.com/pwas/5649025286537216
https://pwa-directory.appspot.com/pwas/5096391307689984

Is there any fix needed?

`Failed to load resource: the server responded with a status of 404 () web-performance-dot-pwa-directory.appspot.com/webpagetestreport/5649025286537216?graph=true`

`{"error":"No WebPageTestReport with that webPageUrlId were found","message":"Check that this methods is allows by the Rest Class","exception_message":"Not Found (404) - No WebPageTestReport with that webPageUrlId were found"}`

**Comment by juliantoledo** [comment]
Hi @iondrimba 

Thank you for submitting them. It usually takes a couple of minutes (up to 2-4hours, depending on backend workload) to get a new PWA rated. Both have been rated as now.

Regards,
Julian

**Comment by iondrimba** [comment]
Thanks for the clarification @juliantoledo 👍
