### ISSUE TITLE
LH viewer

### ISSUE THREAD

**Issue by ebidel** [GoogleChromeLabs/gulliver#475]
Why does the directory ship it's own viewer? Is there something we need to do to make it work with the official online viewer?

**Comment by juliantoledo** [comment]
It would be great if you could make it work to avoid serving our own version.

We would need something similar to your fetch for gistId or something general, this is what we modified in our version:

https://github.com/juliantoledo/lighthouse/commit/d0993fea1d5621789817d5cb4c9f19b26e1ee62f?diff=split

  const pwaDirId = params.get('pwadir');
    if (!pwaDirId) {
      return Promise.resolve();
    }

    return this.getPwaDirFileContentAsJson(pwaDirId).then(reportJson => {
      this._reportIsFromGist = true;
      this._replaceReportHtml(reportJson);
    }).catch(err => logger.error(err.message));
  }

  getPwaDirFileContentAsJson(id) {
    return fetch(`https://web-performance-dot-pwa-directory.appspot.com/lighthousereport/${id}?limit=1`).then(resp => {
      if (!resp.ok) {
        throw new Error(`${resp.status} fetching json from Pwa Directory`);
      }
      return resp.json().then(json => {
        return JSON.parse(json[0].rawData.value);
      });
    });
  }
