### ISSUE TITLE
Add tab for "Installable" PWAs and make it default

### ISSUE THREAD

**Issue by andreban** [GoogleChromeLabs/gulliver#477]
- The installability can be checked as part of [this](https://github.com/GoogleChrome/lighthouse/blob/06a0a45b478565e6fa90636a41d440a41a40b74c/lighthouse-core/audits/webapp-install-banner.js#L99
) audit.
- The results should be sorted by score and date of addition.

**Comment by juliantoledo** [comment]
I guess that would be: 
![screen shot 2018-04-20 at 3 33 42 pm](https://user-images.githubusercontent.com/1920764/39053820-3f59c93c-44b0-11e8-9e2a-36494868d841.png)

**Comment by andreban** [comment]
@slightlyoff, FYI
