### ISSUE TITLE
remove PWA

### ISSUE THREAD

**Issue by Adrianotiger** [GoogleChromeLabs/gulliver#494]
I used Edge to add a PWA. Unfortunately the page didn't show anything (loading bar never stopped), so I used Vivaldi to upload it again.
Now I have 2 apps with the same contents. As I have to log in to put an app, it would be nice if I can remove this app again.

**Comment by juliantoledo** [comment]
Sure @Adrianotiger, can you point me to the PWA?

**Comment by Adrianotiger** [comment]
I uploaded this one with Edge:
https://pwa-directory.appspot.com/pwas/5674341017059328
