### ISSUE TITLE
Create a Share Target

### ISSUE THREAD

**Issue by PaulKinlan** [GoogleChromeLabs/gulliver#500]
I find pwa's as I browse the web, I'd love to share it straight into gulliver so it can get indexed or return the data.

**Comment by juliantoledo** [comment]
This is a great idea, we should definitely implement it.

**Comment by andreban** [comment]
I think we can do this as part of rebuilding the PWA submission process. I've added an endpoint to allow us to do it asynchronously on #501 , and this could also be used to handle the share target.

**Comment by andreban** [comment]
@fstanis, FYI
