### ISSUE TITLE
Save manifest url returning Http 400 - res.body.cancel is not a function

### ISSUE THREAD

**Issue by iondrimba** [GoogleChromeLabs/gulliver#511]
I'm trying to add a manifest url and I keep getting  `{"error":"res.body.cancel is not a function"}` as return data

![http400](https://user-images.githubusercontent.com/178548/44312212-e8d82200-a3ca-11e8-84ba-e6ca1bf8c632.PNG)

The manifest url I'm adding is https://weather.iondrimbafilho.me/manifest.json

**Comment by iondrimba** [comment]
Tried with `https://weather.iondrimbafilho.me/manifest.webmanifest` same problem

**Comment by incognico** [comment]
Same here

**Comment by juliantoledo** [comment]
Seems like a problem with the node-fetch update, I will commit a fix soon, I added both PWAs already.

**Comment by iondrimba** [comment]
Thanks @juliantoledo
