### ISSUE TITLE
Incorrect aspect ratio for app icon

### ISSUE THREAD

**Issue by lamplightdev** [GoogleChromeLabs/gulliver#512]
Hello. I've added a PWA to the directory but the icon is showing in the wrong aspect ratio although all the icons defined in the manifest have the correct aspect ratio:

https://pwa-directory.appspot.com/pwas/6077520841015296

Is there anything I need to do to correct this? Thanks.

**Comment by juliantoledo** [comment]
@lamplightdev thank you for reporting this bug. We will look into it.

Another example:
https://pwa-directory.appspot.com/pwas/5717039152365568
