### ISSUE TITLE
Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by LaPingvino** [GoogleChromeLabs/gulliver#514]
I try to add https://esperanto.github.io/kurso-zagreba-metodo/manifest.json and get the error: `Cannot read property 'Symbol(Symbol.iterator)' of undefined`

**Comment by LaPingvino** [comment]
I saw it was nevertheless correctly added.

**Comment by juliantoledo** [comment]
Thank you for reporting it @LaPingvino, we will look into it if we can reproduce it.
