### ISSUE TITLE
https://pwa-directory.appspot.com/ does not work anymore

### ISSUE THREAD

**Issue by hugues-koolsol** [GoogleChromeLabs/gulliver#519]
Hello
https://pwa-directory.appspot.com/ does not work anymore :-(

As it is a pwa, something is displayed but if you open a new private window, a bug is displayed.

I hope you will fix it :-)
Hugues

**Comment by juliantoledo** [comment]
Hi @hugues-koolsol 

Thank you for letting us know, unfortunately our health checks did not warn us about the issue.

I deployed a temporary fix and it should be working now.

Best regards,
Julian

**Comment by hugues-koolsol** [comment]
Thank you Julian,
you have won a free game on www.koolsol.com ;-)

Best regards
Hugues
