### ISSUE TITLE
Can't log in?

### ISSUE THREAD

**Issue by ChildishGiant** [GoogleChromeLabs/gulliver#523]
Whenever I click on the login button, nothing happens but "Auth not ready!" is logged in chat.

**Comment by incognico** [comment]
I click the user icon button and nothing happens

**Comment by juliantoledo** [comment]
Hi @ChildishGiant @incognico 

What browser are you using? do you have any errors in the javascript console?

Also, please try to hard reload the page to find out if that helps.

Thank you,
Julian

**Comment by incognico** [comment]
![image](https://user-images.githubusercontent.com/2098066/49329704-67745c00-f583-11e8-88ba-26cb9e115a7f.png)

"Auth not ready!" appears after the user icon is clicked.

Chromium Version 72.0.3615.0 (Official Build) (64-bit) Windows 10

**Comment by ChildishGiant** [comment]
For me I'm using Brave and disabling blocking of 3rd-party cookies fixes it. 
![image](https://user-images.githubusercontent.com/13716824/49329999-0a2adb80-f580-11e8-842d-fd3384287c03.png)

**Comment by juliantoledo** [comment]
@ChildishGiant Thank you for sharing.

@incognico It most be the 3rd party cookies as well. Can you check?

**Comment by incognico** [comment]
Ugh 3rd party cookies. Chrome on mobile already has those blocked by default, I don't think the login process should rely on those.
