### ISSUE TITLE
Wrong lighthouse report viewer

### ISSUE THREAD

**Issue by hugues-koolsol** [GoogleChromeLabs/gulliver#524]
Hello Julian

When I go to :
https://pwa-directory.appspot.com/pwas/5510614072164352
and I click on the "lighthouse report viewer" link in the lighthouse block, I reach this page
https://web-performance-dot-pwa-directory.appspot.com/lighthouse-viewer/?pwadir=5510614072164352

which is the report for https://flights.hisgo.com/us/ page instead of the https://todo.koolsol.app/

Can you see what happened ?
Thank you.
Hugues

PS: I did todo.koolsol.app because it is a very small ( and usefull ) app that gives a 100 on all the lighthouse and it is a good reference for my test.

And I did this program : https://github.com/hugues-koolsol/lighthouse
that compute the lighthouse score with this weighting :

10 * pwa score
 4 * performance score
 3 * accessibility score
 2 * best practice score
 1 * seo score

**Comment by juliantoledo** [comment]
@hugues-koolsol Thank you for rising this, it's looks like a clear bug. I will investigate and let you know.

**Comment by hugues-koolsol** [comment]
Hello Julian,
The link https://web-performance-dot-pwa-directory.appspot.com/lighthouse-viewer/?pwadir=5510614072164352
is good now :-)
Did you do something ?
Hugues

**Comment by juliantoledo** [comment]
Hi @hugues-koolsol 

Yes, I fixed the entry in the DB. I could not find a reason of why it happened in the first place. Please let me know if you see the problem again.

Thank you,
Julian

**Comment by hugues-koolsol** [comment]
Hi Julian

I have seen the same problem on this link:
https://pwa-directory.appspot.com/pwas/5076309303099392
which shows the lighthouse report of https://frankly.dk/ instead of https://appsco.pe/

Hugues

**Comment by juliantoledo** [comment]
Hi @hugues-koolsol 

I deleted the duplicated entry.

I think we should probably demote/hide workboxjs.org because is not a PWA anymore.

Cheers,
Julian

**Comment by hugues-koolsol** [comment]
Thank you Julian.
Bye
Hugues

**Comment by hugues-koolsol** [comment]
Hello Julian
I am sorry to tell you that on this page
https://pwa-directory.appspot.com/pwas/4672375163977728
when you click on the "lighthouse report viewer" link in the lighthouse block, 
you see the report for https://www.tvg.com/?   instead of the one for https://www.hfc.com.pl/

Bye
Hugues

**Comment by juliantoledo** [comment]
Hi @hugues-koolsol 

Thank you for sharing this other example. I still need to find why the docker that runs the LightHouse scoring is causing this issue.

Thank you,
Julian
