### ISSUE TITLE
Update Snapdrop URL

### ISSUE THREAD

**Issue by RobinLinus** [GoogleChromeLabs/gulliver#525]
How can I update the URI of [Snapdrop](https://pwa-directory.appspot.com/pwas/5764955169619968)? While https://snpadrop.net was down for a while some fans deployed it under `https://onedoes.github.io/snapdrop/manifest.json` though now the backend of this version is down and [snapdrop.net](https://snapdrop.net) is up again and even runs  version 2.0 with a couple of new features. Could you please change the URI of the Manifest to `https://snapdrop.net/manifest.json` ? 

Thanks a lot!

**Comment by juliantoledo** [comment]
done, thank you for letting us know.
