### ISSUE TITLE
When adding PWA, get network timeout

### ISSUE THREAD

**Issue by Khaoz-Topsy** [GoogleChromeLabs/gulliver#532]
Hi,

I am trying to add my own PWA using the url https://kurtlourens.com/manifest.json and I am receiving a timeout.

What am I doing wrong? 😂

**Comment by juliantoledo** [comment]
@Khaoz-Topsy 

Thank you for reporting this issue, I will debug it and let you know.

**Comment by Khaoz-Topsy** [comment]
Hi! it has been a while 😅, I still can't add https://kurtlourens.com/manifest.json and I have a new site that I would like to add https://tennodex.com/manifest.json. I can't add either of them, I still get the network timeout error 
![image](https://user-images.githubusercontent.com/15005470/58807568-96de5100-8618-11e9-8c9d-eee6ec44ea71.png)

**Comment by juliantoledo** [comment]
Hi @Khaoz-Topsy 

Thank you for reaching out, I added them manually and I will debug the issue to make sure it's solve for future submissions.

Cheers,
Julian
