### ISSUE TITLE
remove PWA

### ISSUE THREAD

**Issue by danmana** [GoogleChromeLabs/gulliver#538]
hi,
we are currently in the process of moving our PWA from one domain to another.
I would like to delete the old entry (as it will be removed soon).
I can't seem to find any option for this from the UI atm.

Old entry: https://pwa-directory.appspot.com/pwas/5769646556971008
New entry: https://pwa-directory.appspot.com/pwas/5937094109298688

Thanks,
Dan

**Comment by juliantoledo** [comment]
Hi @danmana 

I just deleted the old entry.

Cheers,
Julian
