### ISSUE TITLE
different results with the same search

### ISSUE THREAD

**Issue by hugues-koolsol** [GoogleChromeLabs/gulliver#539]
Hello Julian
I have noticed that the same request :

https://pwa-directory.appspot.com/pwas/search?query=koolsol

can give different results launching it in different private browsing windows.

There should be 4 apps but the request returns from 0 to 4 apps.

Hugues

**Comment by juliantoledo** [comment]
Thank you for reporting it, we will look into it.

**Comment by hugues-koolsol** [comment]
Hello Julian,
This bug does not seem to happen these last days, 
Perhaps the on the 30 of July 2019 something went wrong in the infrastructure !
Thanks for your reply.
