### ISSUE TITLE
Ability to refine the score

### ISSUE THREAD

**Issue by hugues-koolsol** [GoogleChromeLabs/gulliver#540]
Hello, when I see the 4 first pwas in the score page :
https://pwa-directory.appspot.com/pwas/score

I notice that there are some apps that do not always give a score of 100 results for the lighthouse score.

Furthermore, score for other audits ( performance, accessibility , ...) are in some cases not so good with warnings.
For example, the first one ( https://web-performance-dot-pwa-directory.appspot.com/lighthouse-viewer/?pwadir=4658345284206592 )
says : Includes front-end JavaScript libraries with known security vulnerabilities.

Could you refine the score page so that it reflects a really good global score.

Thanks.

**Comment by juliantoledo** [comment]
Hi @hugues-koolsol 

You are right, probably we need to change our score's names, Lighthouse has evolve to have more weight in multiple tests and we still call Lighthouse the PWA test. We will look into it.

For the second part, probably we could surface warnings into our PWA page with some annotations in the graph.

Thank you,
Julian
