### ISSUE TITLE
quota exeeded

### ISSUE THREAD

**Issue by hugues-koolsol** [GoogleChromeLabs/gulliver#541]
Hello

When I go there : https://pwa-directory.appspot.com/pwas/newest

I get this message : 

{"code":8,"metadata":{"_internal_repr":{}},"details":"Quota exceeded.","note":"Exception occurred in retry method that was not classified as transient","status":500,"response":"8 RESOURCE_EXHAUSTED: Quota exceeded."}

Is your site too successful ;-) ?

**Comment by juliantoledo** [comment]
Hi @hugues-koolsol 

Thank you for reporting it, I don't see many errors in our logs. I will double check but it seems it was something isolated.

Cheers,
Julian.

**Comment by hugues-koolsol** [comment]
Hello Julian.
I had the same message this morning.

**Comment by hugues-koolsol** [comment]
Hello Julian
This morning on : https://pwa-directory.appspot.com/
I had a reply : 502 Bad Gateway
