### ISSUE TITLE
The graphic of the lighthouse score is not updated

### ISSUE THREAD

**Issue by hugues-koolsol** [GoogleChromeLabs/gulliver#545]
Hello, on this page : 
https://pwa-directory.appspot.com/pwas/5159185788436480
has not been updated since 2019-11-10

**Comment by carlosvin** [comment]
Similar issue here, recently registered PWAs are not generating this report, for example: 

- https://pwa-directory.appspot.com/pwas/6448541046800384
- https://pwa-directory.appspot.com/pwas/5749031719010304

**Comment by juliantoledo** [comment]
We will probably remove LH graphs and use the information from PageSpeedInsights.
